### ISSUE TITLE
keeping record of personal score

### ISSUE THREAD

**Issue by RR-Ralefaso** [Keokeditse/Astro-Intelligence#1]
we plan to find a way to keep record of your best score and since we don't know databases id like us to use files any one can work on this

you can use the demo code but create a copy to not mess up the original
@Keokeditse 
@justnobody1011 
@orahhh

**Comment by Keokeditse** [comment]
Ok, consider it done.

**Comment by justnobody1011** [comment]
@RR-Ralefaso, Is the demo code available on GitHub? I found something on tracking the scores but I'm still to test it.

**Comment by RR-Ralefaso** [comment]
> @RR-Ralefaso, Is the demo code available on GitHub? I found something on tracking the scores but I'm still to test it.
> 

yes
