### ISSUE TITLE
creating more snakes 

### ISSUE THREAD

**Issue by UnusualRalph** [Keokeditse/Astro-Intelligence#2]
so yayy hope everyone is doing well
I've been working on creating more snake but it's kind of tedious so if possible just try to make more snakes or suggest how we should approach it .

have an amazing day

**Comment by UnusualRalph** [comment]
and move around randomly forgot to add that 
and please document your code don't want to deal with not knowing what's going on

**Comment by orahhh** [comment]
got it

**Comment by RR-Ralefaso** [comment]
fixing this problem by adding obstacles
